# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac71caf461c828e5ef02036dc53b35b50bbc9698cd164e116a24f67afaf2832ccb38cd16ecba6e6c4142854eb6254b8a5be914ee2ff81dddc8e5df6c661db24c

test:
  secret_key_base: 7a802d93101d6d8ec2d305536215c0a907f8da812d5766d079fe6f8eb14e9a414370c0d8a8c5700eb586927dc6b730580ff0aa0a8efb6df7a6ce2020123fd871

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
